//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSConfig) DeepCopyInto(out *AWSConfig) {
	*out = *in
	if in.AWSAccessKeySecret != nil {
		in, out := &in.AWSAccessKeySecret, &out.AWSAccessKeySecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSConfig.
func (in *AWSConfig) DeepCopy() *AWSConfig {
	if in == nil {
		return nil
	}
	out := new(AWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.AddToSet != nil {
		in, out := &in.AddToSet, &out.AddToSet
		*out = new(SetAction)
		**out = **in
	}
	if in.RemoveFromSet != nil {
		in, out := &in.RemoveFromSet, &out.RemoveFromSet
		*out = new(SetAction)
		**out = **in
	}
	if in.SetVariable != nil {
		in, out := &in.SetVariable, &out.SetVariable
		*out = new(ScalarAction)
		**out = **in
	}
	if in.AddToMap != nil {
		in, out := &in.AddToMap, &out.AddToMap
		*out = new(MapAction)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveFromMap != nil {
		in, out := &in.RemoveFromMap, &out.RemoveFromMap
		*out = new(MapAction)
		(*in).DeepCopyInto(*out)
	}
	if in.CallWebhook != nil {
		in, out := &in.CallWebhook, &out.CallWebhook
		*out = new(CallWebhookAction)
		(*in).DeepCopyInto(*out)
	}
	if in.DeployReplay != nil {
		in, out := &in.DeployReplay, &out.DeployReplay
		*out = new(DeployReplayAction)
		(*in).DeepCopyInto(*out)
	}
	if in.CleanUpReplay != nil {
		in, out := &in.CleanUpReplay, &out.CleanUpReplay
		*out = new(CleanUpReplayAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLogstreamConfig) DeepCopyInto(out *AuditLogstreamConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLogstreamConfig.
func (in *AuditLogstreamConfig) DeepCopy() *AuditLogstreamConfig {
	if in == nil {
		return nil
	}
	out := new(AuditLogstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutomationRule) DeepCopyInto(out *AutomationRule) {
	*out = *in
	in.When.DeepCopyInto(&out.When)
	if in.Then != nil {
		in, out := &in.Then, &out.Then
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutomationRule.
func (in *AutomationRule) DeepCopy() *AutomationRule {
	if in == nil {
		return nil
	}
	out := new(AutomationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CallWebhookAction) DeepCopyInto(out *CallWebhookAction) {
	*out = *in
	in.URL.DeepCopyInto(&out.URL)
	if in.PayloadTemplate != nil {
		in, out := &in.PayloadTemplate, &out.PayloadTemplate
		*out = new(StringOrFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.TemplateValues != nil {
		in, out := &in.TemplateValues, &out.TemplateValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TemplateValuesFrom != nil {
		in, out := &in.TemplateValuesFrom, &out.TemplateValuesFrom
		*out = make(map[string]ValueFromSource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HeadersFrom != nil {
		in, out := &in.HeadersFrom, &out.HeadersFrom
		*out = make(map[string]ValueFromSource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CallWebhookAction.
func (in *CallWebhookAction) DeepCopy() *CallWebhookAction {
	if in == nil {
		return nil
	}
	out := new(CallWebhookAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanUpReplayAction) DeepCopyInto(out *CleanUpReplayAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanUpReplayAction.
func (in *CleanUpReplayAction) DeepCopy() *CleanUpReplayAction {
	if in == nil {
		return nil
	}
	out := new(CleanUpReplayAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.EvaluationInterval != nil {
		in, out := &in.EvaluationInterval, &out.EvaluationInterval
		*out = new(monitoringv1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployReplayAction) DeepCopyInto(out *DeployReplayAction) {
	*out = *in
	in.ReplaySpec.DeepCopyInto(&out.ReplaySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployReplayAction.
func (in *DeployReplayAction) DeepCopy() *DeployReplayAction {
	if in == nil {
		return nil
	}
	out := new(DeployReplayAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressService) DeepCopyInto(out *IngressService) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressService.
func (in *IngressService) DeepCopy() *IngressService {
	if in == nil {
		return nil
	}
	out := new(IngressService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JoinTransformer) DeepCopyInto(out *JoinTransformer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JoinTransformer.
func (in *JoinTransformer) DeepCopy() *JoinTransformer {
	if in == nil {
		return nil
	}
	out := new(JoinTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsConfig) DeepCopyInto(out *LogsConfig) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3LogsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Otlp != nil {
		in, out := &in.Otlp, &out.Otlp
		*out = new(OtlpLogsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsConfig.
func (in *LogsConfig) DeepCopy() *LogsConfig {
	if in == nil {
		return nil
	}
	out := new(LogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogstreamConfig) DeepCopyInto(out *LogstreamConfig) {
	*out = *in
	if in.MinSeverity != nil {
		in, out := &in.MinSeverity, &out.MinSeverity
		*out = new(SeverityLevel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogstreamConfig.
func (in *LogstreamConfig) DeepCopy() *LogstreamConfig {
	if in == nil {
		return nil
	}
	out := new(LogstreamConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapAction) DeepCopyInto(out *MapAction) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapAction.
func (in *MapAction) DeepCopy() *MapAction {
	if in == nil {
		return nil
	}
	out := new(MapAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollector) DeepCopyInto(out *MdaiCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollector.
func (in *MdaiCollector) DeepCopy() *MdaiCollector {
	if in == nil {
		return nil
	}
	out := new(MdaiCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollectorList) DeepCopyInto(out *MdaiCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollectorList.
func (in *MdaiCollectorList) DeepCopy() *MdaiCollectorList {
	if in == nil {
		return nil
	}
	out := new(MdaiCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollectorSpec) DeepCopyInto(out *MdaiCollectorSpec) {
	*out = *in
	if in.AWSConfig != nil {
		in, out := &in.AWSConfig, &out.AWSConfig
		*out = new(AWSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(LogsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollectorSpec.
func (in *MdaiCollectorSpec) DeepCopy() *MdaiCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiCollectorStatus) DeepCopyInto(out *MdaiCollectorStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiCollectorStatus.
func (in *MdaiCollectorStatus) DeepCopy() *MdaiCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDal) DeepCopyInto(out *MdaiDal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDal.
func (in *MdaiDal) DeepCopy() *MdaiDal {
	if in == nil {
		return nil
	}
	out := new(MdaiDal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiDal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalAWSConfig) DeepCopyInto(out *MdaiDalAWSConfig) {
	*out = *in
	out.Credentials = in.Credentials
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalAWSConfig.
func (in *MdaiDalAWSConfig) DeepCopy() *MdaiDalAWSConfig {
	if in == nil {
		return nil
	}
	out := new(MdaiDalAWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalAWSCredentials) DeepCopyInto(out *MdaiDalAWSCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalAWSCredentials.
func (in *MdaiDalAWSCredentials) DeepCopy() *MdaiDalAWSCredentials {
	if in == nil {
		return nil
	}
	out := new(MdaiDalAWSCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalImageSpec) DeepCopyInto(out *MdaiDalImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalImageSpec.
func (in *MdaiDalImageSpec) DeepCopy() *MdaiDalImageSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiDalImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalList) DeepCopyInto(out *MdaiDalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiDal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalList.
func (in *MdaiDalList) DeepCopy() *MdaiDalList {
	if in == nil {
		return nil
	}
	out := new(MdaiDalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiDalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalS3Config) DeepCopyInto(out *MdaiDalS3Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalS3Config.
func (in *MdaiDalS3Config) DeepCopy() *MdaiDalS3Config {
	if in == nil {
		return nil
	}
	out := new(MdaiDalS3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalSpec) DeepCopyInto(out *MdaiDalSpec) {
	*out = *in
	out.S3 = in.S3
	out.AWS = in.AWS
	if in.ImageSpec != nil {
		in, out := &in.ImageSpec, &out.ImageSpec
		*out = new(MdaiDalImageSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalSpec.
func (in *MdaiDalSpec) DeepCopy() *MdaiDalSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiDalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiDalStatus) DeepCopyInto(out *MdaiDalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastSyncedTime.DeepCopyInto(&out.LastSyncedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiDalStatus.
func (in *MdaiDalStatus) DeepCopy() *MdaiDalStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiDalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHub) DeepCopyInto(out *MdaiHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHub.
func (in *MdaiHub) DeepCopy() *MdaiHub {
	if in == nil {
		return nil
	}
	out := new(MdaiHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubList) DeepCopyInto(out *MdaiHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubList.
func (in *MdaiHubList) DeepCopy() *MdaiHubList {
	if in == nil {
		return nil
	}
	out := new(MdaiHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubSpec) DeepCopyInto(out *MdaiHubSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]Variable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrometheusAlerts != nil {
		in, out := &in.PrometheusAlerts, &out.PrometheusAlerts
		*out = make([]PrometheusAlert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]AutomationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubSpec.
func (in *MdaiHubSpec) DeepCopy() *MdaiHubSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiHubStatus) DeepCopyInto(out *MdaiHubStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiHubStatus.
func (in *MdaiHubStatus) DeepCopy() *MdaiHubStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiIngress) DeepCopyInto(out *MdaiIngress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiIngress.
func (in *MdaiIngress) DeepCopy() *MdaiIngress {
	if in == nil {
		return nil
	}
	out := new(MdaiIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiIngress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiIngressList) DeepCopyInto(out *MdaiIngressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiIngress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiIngressList.
func (in *MdaiIngressList) DeepCopy() *MdaiIngressList {
	if in == nil {
		return nil
	}
	out := new(MdaiIngressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiIngressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiIngressSpec) DeepCopyInto(out *MdaiIngressSpec) {
	*out = *in
	out.OtelCollector = in.OtelCollector
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IngressClassName != nil {
		in, out := &in.IngressClassName, &out.IngressClassName
		*out = new(string)
		**out = **in
	}
	if in.GrpcService != nil {
		in, out := &in.GrpcService, &out.GrpcService
		*out = new(IngressService)
		(*in).DeepCopyInto(*out)
	}
	if in.NonGrpcService != nil {
		in, out := &in.NonGrpcService, &out.NonGrpcService
		*out = new(IngressService)
		(*in).DeepCopyInto(*out)
	}
	if in.CollectorEndpoints != nil {
		in, out := &in.CollectorEndpoints, &out.CollectorEndpoints
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiIngressSpec.
func (in *MdaiIngressSpec) DeepCopy() *MdaiIngressSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiIngressStatus) DeepCopyInto(out *MdaiIngressStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiIngressStatus.
func (in *MdaiIngressStatus) DeepCopy() *MdaiIngressStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiIngressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserver) DeepCopyInto(out *MdaiObserver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserver.
func (in *MdaiObserver) DeepCopy() *MdaiObserver {
	if in == nil {
		return nil
	}
	out := new(MdaiObserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiObserver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserverList) DeepCopyInto(out *MdaiObserverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiObserver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserverList.
func (in *MdaiObserverList) DeepCopy() *MdaiObserverList {
	if in == nil {
		return nil
	}
	out := new(MdaiObserverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiObserverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserverSpec) DeepCopyInto(out *MdaiObserverSpec) {
	*out = *in
	if in.Observers != nil {
		in, out := &in.Observers, &out.Observers
		*out = make([]Observer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ObserverResource.DeepCopyInto(&out.ObserverResource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserverSpec.
func (in *MdaiObserverSpec) DeepCopy() *MdaiObserverSpec {
	if in == nil {
		return nil
	}
	out := new(MdaiObserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiObserverStatus) DeepCopyInto(out *MdaiObserverStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiObserverStatus.
func (in *MdaiObserverStatus) DeepCopy() *MdaiObserverStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiObserverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplay) DeepCopyInto(out *MdaiReplay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplay.
func (in *MdaiReplay) DeepCopy() *MdaiReplay {
	if in == nil {
		return nil
	}
	out := new(MdaiReplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiReplay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayAwsConfig) DeepCopyInto(out *MdaiReplayAwsConfig) {
	*out = *in
	if in.AWSAccessKeySecret != nil {
		in, out := &in.AWSAccessKeySecret, &out.AWSAccessKeySecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayAwsConfig.
func (in *MdaiReplayAwsConfig) DeepCopy() *MdaiReplayAwsConfig {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayAwsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayDestinationConfiguration) DeepCopyInto(out *MdaiReplayDestinationConfiguration) {
	*out = *in
	if in.OtlpHttp != nil {
		in, out := &in.OtlpHttp, &out.OtlpHttp
		*out = new(MdaiReplayOtlpHttpDestinationConfiguration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayDestinationConfiguration.
func (in *MdaiReplayDestinationConfiguration) DeepCopy() *MdaiReplayDestinationConfiguration {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayDestinationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayList) DeepCopyInto(out *MdaiReplayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MdaiReplay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayList.
func (in *MdaiReplayList) DeepCopy() *MdaiReplayList {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MdaiReplayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayOtlpHttpDestinationConfiguration) DeepCopyInto(out *MdaiReplayOtlpHttpDestinationConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayOtlpHttpDestinationConfiguration.
func (in *MdaiReplayOtlpHttpDestinationConfiguration) DeepCopy() *MdaiReplayOtlpHttpDestinationConfiguration {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayOtlpHttpDestinationConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayResourceConfiguration) DeepCopyInto(out *MdaiReplayResourceConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayResourceConfiguration.
func (in *MdaiReplayResourceConfiguration) DeepCopy() *MdaiReplayResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayResourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayS3Configuration) DeepCopyInto(out *MdaiReplayS3Configuration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayS3Configuration.
func (in *MdaiReplayS3Configuration) DeepCopy() *MdaiReplayS3Configuration {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayS3Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplaySourceConfiguration) DeepCopyInto(out *MdaiReplaySourceConfiguration) {
	*out = *in
	if in.AWSConfig != nil {
		in, out := &in.AWSConfig, &out.AWSConfig
		*out = new(MdaiReplayAwsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(MdaiReplayS3Configuration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplaySourceConfiguration.
func (in *MdaiReplaySourceConfiguration) DeepCopy() *MdaiReplaySourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(MdaiReplaySourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplaySpec) DeepCopyInto(out *MdaiReplaySpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Destination.DeepCopyInto(&out.Destination)
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplaySpec.
func (in *MdaiReplaySpec) DeepCopy() *MdaiReplaySpec {
	if in == nil {
		return nil
	}
	out := new(MdaiReplaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MdaiReplayStatus) DeepCopyInto(out *MdaiReplayStatus) {
	*out = *in
	if in.LastUpdatedTime != nil {
		in, out := &in.LastUpdatedTime, &out.LastUpdatedTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MdaiReplayStatus.
func (in *MdaiReplayStatus) DeepCopy() *MdaiReplayStatus {
	if in == nil {
		return nil
	}
	out := new(MdaiReplayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Observer) DeepCopyInto(out *Observer) {
	*out = *in
	if in.LabelResourceAttributes != nil {
		in, out := &in.LabelResourceAttributes, &out.LabelResourceAttributes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CountMetricName != nil {
		in, out := &in.CountMetricName, &out.CountMetricName
		*out = new(string)
		**out = **in
	}
	if in.BytesMetricName != nil {
		in, out := &in.BytesMetricName, &out.BytesMetricName
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(ObserverFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Observer.
func (in *Observer) DeepCopy() *Observer {
	if in == nil {
		return nil
	}
	out := new(Observer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverFilter) DeepCopyInto(out *ObserverFilter) {
	*out = *in
	if in.ErrorMode != nil {
		in, out := &in.ErrorMode, &out.ErrorMode
		*out = new(string)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(ObserverLogsFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverFilter.
func (in *ObserverFilter) DeepCopy() *ObserverFilter {
	if in == nil {
		return nil
	}
	out := new(ObserverFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverLogsFilter) DeepCopyInto(out *ObserverLogsFilter) {
	*out = *in
	if in.LogRecord != nil {
		in, out := &in.LogRecord, &out.LogRecord
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverLogsFilter.
func (in *ObserverLogsFilter) DeepCopy() *ObserverLogsFilter {
	if in == nil {
		return nil
	}
	out := new(ObserverLogsFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObserverResource) DeepCopyInto(out *ObserverResource) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.GrpcReceiverMaxMsgSize != nil {
		in, out := &in.GrpcReceiverMaxMsgSize, &out.GrpcReceiverMaxMsgSize
		*out = new(uint64)
		**out = **in
	}
	if in.OwnLogsOtlpEndpoint != nil {
		in, out := &in.OwnLogsOtlpEndpoint, &out.OwnLogsOtlpEndpoint
		*out = new(string)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObserverResource.
func (in *ObserverResource) DeepCopy() *ObserverResource {
	if in == nil {
		return nil
	}
	out := new(ObserverResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelColRef) DeepCopyInto(out *OtelColRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelColRef.
func (in *OtelColRef) DeepCopy() *OtelColRef {
	if in == nil {
		return nil
	}
	out := new(OtelColRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelMdaiIngressComb) DeepCopyInto(out *OtelMdaiIngressComb) {
	*out = *in
	in.Otelcol.DeepCopyInto(&out.Otelcol)
	in.MdaiIngress.DeepCopyInto(&out.MdaiIngress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelMdaiIngressComb.
func (in *OtelMdaiIngressComb) DeepCopy() *OtelMdaiIngressComb {
	if in == nil {
		return nil
	}
	out := new(OtelMdaiIngressComb)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtlpLogsConfig) DeepCopyInto(out *OtlpLogsConfig) {
	*out = *in
	if in.AuditLogs != nil {
		in, out := &in.AuditLogs, &out.AuditLogs
		*out = new(AuditLogstreamConfig)
		**out = **in
	}
	if in.CollectorLogs != nil {
		in, out := &in.CollectorLogs, &out.CollectorLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HubLogs != nil {
		in, out := &in.HubLogs, &out.HubLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtherLogs != nil {
		in, out := &in.OtherLogs, &out.OtherLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtlpLogsConfig.
func (in *OtlpLogsConfig) DeepCopy() *OtlpLogsConfig {
	if in == nil {
		return nil
	}
	out := new(OtlpLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusAlert) DeepCopyInto(out *PrometheusAlert) {
	*out = *in
	out.Expr = in.Expr
	if in.For != nil {
		in, out := &in.For, &out.For
		*out = new(monitoringv1.Duration)
		**out = **in
	}
	if in.KeepFiringFor != nil {
		in, out := &in.KeepFiringFor, &out.KeepFiringFor
		*out = new(monitoringv1.NonEmptyDuration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusAlert.
func (in *PrometheusAlert) DeepCopy() *PrometheusAlert {
	if in == nil {
		return nil
	}
	out := new(PrometheusAlert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3LogsConfig) DeepCopyInto(out *S3LogsConfig) {
	*out = *in
	if in.AuditLogs != nil {
		in, out := &in.AuditLogs, &out.AuditLogs
		*out = new(AuditLogstreamConfig)
		**out = **in
	}
	if in.CollectorLogs != nil {
		in, out := &in.CollectorLogs, &out.CollectorLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.HubLogs != nil {
		in, out := &in.HubLogs, &out.HubLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OtherLogs != nil {
		in, out := &in.OtherLogs, &out.OtherLogs
		*out = new(LogstreamConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3LogsConfig.
func (in *S3LogsConfig) DeepCopy() *S3LogsConfig {
	if in == nil {
		return nil
	}
	out := new(S3LogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalarAction) DeepCopyInto(out *ScalarAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalarAction.
func (in *ScalarAction) DeepCopy() *ScalarAction {
	if in == nil {
		return nil
	}
	out := new(ScalarAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Serializer) DeepCopyInto(out *Serializer) {
	*out = *in
	if in.Transformers != nil {
		in, out := &in.Transformers, &out.Transformers
		*out = make([]VariableTransformer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Serializer.
func (in *Serializer) DeepCopy() *Serializer {
	if in == nil {
		return nil
	}
	out := new(Serializer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetAction) DeepCopyInto(out *SetAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetAction.
func (in *SetAction) DeepCopy() *SetAction {
	if in == nil {
		return nil
	}
	out := new(SetAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringOrFrom) DeepCopyInto(out *StringOrFrom) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueFromSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringOrFrom.
func (in *StringOrFrom) DeepCopy() *StringOrFrom {
	if in == nil {
		return nil
	}
	out := new(StringOrFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidation) DeepCopyInto(out *TelemetryValidation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidation.
func (in *TelemetryValidation) DeepCopy() *TelemetryValidation {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelemetryValidation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationCollectorRef) DeepCopyInto(out *TelemetryValidationCollectorRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationCollectorRef.
func (in *TelemetryValidationCollectorRef) DeepCopy() *TelemetryValidationCollectorRef {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationCollectorRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationExporterRewrite) DeepCopyInto(out *TelemetryValidationExporterRewrite) {
	*out = *in
	if in.MatchExporterPrefixes != nil {
		in, out := &in.MatchExporterPrefixes, &out.MatchExporterPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Set != nil {
		in, out := &in.Set, &out.Set
		*out = make(map[string]apiextensionsv1.JSON, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ReplaceStrings != nil {
		in, out := &in.ReplaceStrings, &out.ReplaceStrings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationExporterRewrite.
func (in *TelemetryValidationExporterRewrite) DeepCopy() *TelemetryValidationExporterRewrite {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationExporterRewrite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationIngressCaptureSpec) DeepCopyInto(out *TelemetryValidationIngressCaptureSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationIngressCaptureSpec.
func (in *TelemetryValidationIngressCaptureSpec) DeepCopy() *TelemetryValidationIngressCaptureSpec {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationIngressCaptureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationList) DeepCopyInto(out *TelemetryValidationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TelemetryValidation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationList.
func (in *TelemetryValidationList) DeepCopy() *TelemetryValidationList {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TelemetryValidationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationShadowCollectorSpec) DeepCopyInto(out *TelemetryValidationShadowCollectorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationShadowCollectorSpec.
func (in *TelemetryValidationShadowCollectorSpec) DeepCopy() *TelemetryValidationShadowCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationShadowCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationSpec) DeepCopyInto(out *TelemetryValidationSpec) {
	*out = *in
	out.CollectorRef = in.CollectorRef
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]TelemetrySignal, len(*in))
		copy(*out, *in)
	}
	in.Validator.DeepCopyInto(&out.Validator)
	out.ShadowCollector = in.ShadowCollector
	out.IngressCapture = in.IngressCapture
	if in.ExporterRewrites != nil {
		in, out := &in.ExporterRewrites, &out.ExporterRewrites
		*out = make([]TelemetryValidationExporterRewrite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationSpec.
func (in *TelemetryValidationSpec) DeepCopy() *TelemetryValidationSpec {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationStatus) DeepCopyInto(out *TelemetryValidationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveSignals != nil {
		in, out := &in.ActiveSignals, &out.ActiveSignals
		*out = make([]TelemetrySignal, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationStatus.
func (in *TelemetryValidationStatus) DeepCopy() *TelemetryValidationStatus {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryValidationValidatorSpec) DeepCopyInto(out *TelemetryValidationValidatorSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryValidationValidatorSpec.
func (in *TelemetryValidationValidatorSpec) DeepCopy() *TelemetryValidationValidatorSpec {
	if in == nil {
		return nil
	}
	out := new(TelemetryValidationValidatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFromSource) DeepCopyInto(out *ValueFromSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFromSource.
func (in *ValueFromSource) DeepCopy() *ValueFromSource {
	if in == nil {
		return nil
	}
	out := new(ValueFromSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Variable) DeepCopyInto(out *Variable) {
	*out = *in
	if in.VariableRefs != nil {
		in, out := &in.VariableRefs, &out.VariableRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SerializeAs != nil {
		in, out := &in.SerializeAs, &out.SerializeAs
		*out = new([]Serializer)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Serializer, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Variable.
func (in *Variable) DeepCopy() *Variable {
	if in == nil {
		return nil
	}
	out := new(Variable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VariableTransformer) DeepCopyInto(out *VariableTransformer) {
	*out = *in
	if in.Join != nil {
		in, out := &in.Join, &out.Join
		*out = new(JoinTransformer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VariableTransformer.
func (in *VariableTransformer) DeepCopy() *VariableTransformer {
	if in == nil {
		return nil
	}
	out := new(VariableTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *When) DeepCopyInto(out *When) {
	*out = *in
	if in.AlertName != nil {
		in, out := &in.AlertName, &out.AlertName
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.VariableUpdated != nil {
		in, out := &in.VariableUpdated, &out.VariableUpdated
		*out = new(string)
		**out = **in
	}
	if in.UpdateType != nil {
		in, out := &in.UpdateType, &out.UpdateType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new When.
func (in *When) DeepCopy() *When {
	if in == nil {
		return nil
	}
	out := new(When)
	in.DeepCopyInto(out)
	return out
}
