signals:
  metrics:
    required_attributes:
      - metric_name
      - point_timestamp
      - point_value
      - service
      - env
  traces:
    required_attributes:
      - env
      - service
      - name: operation_name
        compare: presence_only
      - name: resource_name
        compare: presence_only
      - trace_id
  logs:
    required_attributes:
      - name: ddsource
        compare: presence_only
      - name: hostname
        compare: presence_only
      - service
      - message
      - status
      - name: timestamp
        compare: presence_only
